import { styled } from "@linaria/react";
import React from "react";
import { render } from "react-dom";

const colors = {
  aliceblue: "#f0f8ff",
  antiquewhite: "#faebd7",
  aqua: "#00ffff",
  aquamarine: "#7fffd4",
  azure: "#f0ffff",
  beige: "#f5f5dc",
  bisque: "#ffe4c4",
  black: "#000000",
  blanchedalmond: "#ffebcd",
  blue: "#0000ff",
  blueviolet: "#8a2be2",
  brown: "#a52a2a",
  burlywood: "#deb887",
  cadetblue: "#5f9ea0",
  chartreuse: "#7fff00",
  chocolate: "#d2691e",
  coral: "#ff7f50",
  cornflowerblue: "#6495ed",
  cornsilk: "#fff8dc",
  crimson: "#dc143c",
  cyan: "#00ffff",
  darkblue: "#00008b",
  darkcyan: "#008b8b",
  darkgoldenrod: "#b8860b",
  darkgray: "#a9a9a9",
  darkgreen: "#006400",
  darkgrey: "#a9a9a9",
  darkkhaki: "#bdb76b",
  darkmagenta: "#8b008b",
  darkolivegreen: "#556b2f",
  darkorange: "#ff8c00",
  darkorchid: "#9932cc",
  darkred: "#8b0000",
  darksalmon: "#e9967a",
  darkseagreen: "#8fbc8f",
  darkslateblue: "#483d8b",
  darkslategray: "#2f4f4f",
  darkslategrey: "#2f4f4f",
  darkturquoise: "#00ced1",
  darkviolet: "#9400d3",
  deeppink: "#ff1493",
  deepskyblue: "#00bfff",
  dimgray: "#696969",
  dimgrey: "#696969",
  dodgerblue: "#1e90ff",
  firebrick: "#b22222",
  floralwhite: "#fffaf0",
  forestgreen: "#228b22",
  fuchsia: "#ff00ff",
  gainsboro: "#dcdcdc",
  ghostwhite: "#f8f8ff",
  gold: "#ffd700",
  goldenrod: "#daa520",
  gray: "#808080",
  green: "#008000",
  greenyellow: "#adff2f",
  grey: "#808080",
  honeydew: "#f0fff0",
  hotpink: "#ff69b4",
  indianred: "#cd5c5c",
  indigo: "#4b0082",
  ivory: "#fffff0",
  khaki: "#f0e68c",
  lavender: "#e6e6fa",
  lavenderblush: "#fff0f5",
  lawngreen: "#7cfc00",
  lemonchiffon: "#fffacd",
  lightblue: "#add8e6",
  lightcoral: "#f08080",
  lightcyan: "#e0ffff",
  lightgoldenrodyellow: "#fafad2",
  lightgray: "#d3d3d3",
  lightgreen: "#90ee90",
  lightgrey: "#d3d3d3",
  lightpink: "#ffb6c1",
  lightsalmon: "#ffa07a",
  lightseagreen: "#20b2aa",
};

const mappedColors = {
  aliceblue: colors.aliceblue,
  antiquewhite: colors.antiquewhite,
  aqua: colors.aqua,
  aquamarine: colors.aquamarine,
  azure: colors.azure,
  beige: colors.beige,
  bisque: colors.bisque,
  black: colors.black,
  blanchedalmond: colors.blanchedalmond,
  blue: colors.blue,
  blueviolet: colors.blueviolet,
  brown: colors.brown,
  burlywood: colors.burlywood,
  cadetblue: colors.cadetblue,
  chartreuse: colors.chartreuse,
  chocolate: colors.chocolate,
  coral: colors.coral,
  cornflowerblue: colors.cornflowerblue,
  cornsilk: colors.cornsilk,
  crimson: colors.crimson,
  cyan: colors.cyan,
  darkblue: colors.darkblue,
  darkcyan: colors.darkcyan,
  darkgoldenrod: colors.darkgoldenrod,
  darkgray: colors.darkgray,
  darkgreen: colors.darkgreen,
  darkgrey: colors.darkgrey,
  darkkhaki: colors.darkkhaki,
  darkmagenta: colors.darkmagenta,
  darkolivegreen: colors.darkolivegreen,
  darkorange: colors.darkorange,
  darkorchid: colors.darkorchid,
  darkred: colors.darkred,
  darksalmon: colors.darksalmon,
  darkseagreen: colors.darkseagreen,
  darkslateblue: colors.darkslateblue,
  darkslategray: colors.darkslategray,
  darkslategrey: colors.darkslategrey,
  darkturquoise: colors.darkturquoise,
  darkviolet: colors.darkviolet,
  deeppink: colors.deeppink,
  deepskyblue: colors.deepskyblue,
  dimgray: colors.dimgray,
  dimgrey: colors.dimgrey,
  dodgerblue: colors.dodgerblue,
  firebrick: colors.firebrick,
  floralwhite: colors.floralwhite,
  forestgreen: colors.forestgreen,
  fuchsia: colors.fuchsia,
  gainsboro: colors.gainsboro,
  ghostwhite: colors.ghostwhite,
  gold: colors.gold,
  goldenrod: colors.goldenrod,
  gray: colors.gray,
  green: colors.green,
  greenyellow: colors.greenyellow,
  grey: colors.grey,
  honeydew: colors.honeydew,
  hotpink: colors.hotpink,
  indianred: colors.indianred,
  indigo: colors.indigo,
  ivory: colors.ivory,
  khaki: colors.khaki,
  lavender: colors.lavender,
  lavenderblush: colors.lavenderblush,
  lawngreen: colors.lawngreen,
  lemonchiffon: colors.lemonchiffon,
  lightblue: colors.lightblue,
  lightcoral: colors.lightcoral,
  lightcyan: colors.lightcyan,
  lightgoldenrodyellow: colors.lightgoldenrodyellow,
  lightgray: colors.lightgray,
  lightgreen: colors.lightgreen,
  lightgrey: colors.lightgrey,
  lightpink: colors.lightpink,
  lightsalmon: colors.lightsalmon,
  lightseagreen: colors.lightseagreen,
};

const mapColorVars = colors => 
  Object.keys(colors).map(key => `--${key}: ${colors[key]}`).join(";\n");

const App = styled.div`
  :global() {
    body {
      ${mapColorVars(mappedColors)};
    }
  }

  color: var(--lightpink);
`;

render(<App>Testing 1, 2, 3...</App>, document.querySelector("#root"));
